// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// par_cor_vecs
double par_cor_vecs(NumericVector& x, NumericVector& y, int threads);
RcppExport SEXP OMPutils_par_cor_vecs(SEXP xSEXP, SEXP ySEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(par_cor_vecs(x, y, threads));
    return rcpp_result_gen;
END_RCPP
}
// par_cor_matrix
NumericMatrix par_cor_matrix(NumericMatrix& X, int threads);
RcppExport SEXP OMPutils_par_cor_matrix(SEXP XSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(par_cor_matrix(X, threads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_dist
SEXP rcpp_dist(NumericMatrix& x, std::string method, bool na_rm, int threads, bool display_progress);
RcppExport SEXP OMPutils_rcpp_dist(SEXP xSEXP, SEXP methodSEXP, SEXP na_rmSEXP, SEXP threadsSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_dist(x, method, na_rm, threads, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_as_numeric_matrix
NumericMatrix Rcpp_as_numeric_matrix(DataFrame x);
RcppExport SEXP OMPutils_Rcpp_as_numeric_matrix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_as_numeric_matrix(x));
    return rcpp_result_gen;
END_RCPP
}
// par_mean
double par_mean(NumericVector& x, bool na_rm, int threads);
RcppExport SEXP OMPutils_par_mean(SEXP xSEXP, SEXP na_rmSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(par_mean(x, na_rm, threads));
    return rcpp_result_gen;
END_RCPP
}
// par_colMeans
NumericVector par_colMeans(NumericMatrix& x, bool na_rm, int threads, bool display_progress);
RcppExport SEXP OMPutils_par_colMeans(SEXP xSEXP, SEXP na_rmSEXP, SEXP threadsSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(par_colMeans(x, na_rm, threads, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// par_rank
NumericVector par_rank(NumericVector& x, int threads);
RcppExport SEXP OMPutils_par_rank(SEXP xSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(par_rank(x, threads));
    return rcpp_result_gen;
END_RCPP
}
// par_sort
NumericVector par_sort(NumericVector& x);
RcppExport SEXP OMPutils_par_sort(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(par_sort(x));
    return rcpp_result_gen;
END_RCPP
}
// par_sum
double par_sum(NumericVector& x, bool na_rm, int threads);
RcppExport SEXP OMPutils_par_sum(SEXP xSEXP, SEXP na_rmSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(par_sum(x, na_rm, threads));
    return rcpp_result_gen;
END_RCPP
}
// par_colSums
SEXP par_colSums(NumericMatrix& x, bool na_rm, int threads, bool display_progress);
RcppExport SEXP OMPutils_par_colSums(SEXP xSEXP, SEXP na_rmSEXP, SEXP threadsSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(par_colSums(x, na_rm, threads, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// par_var
double par_var(NumericVector x, bool na_rm, int threads);
RcppExport SEXP OMPutils_par_var(SEXP xSEXP, SEXP na_rmSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(par_var(x, na_rm, threads));
    return rcpp_result_gen;
END_RCPP
}
// par_colVars
NumericVector par_colVars(const NumericMatrix& x, bool na_rm, int threads);
RcppExport SEXP OMPutils_par_colVars(SEXP xSEXP, SEXP na_rmSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(par_colVars(x, na_rm, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"OMPutils_par_cor_vecs", (DL_FUNC) &OMPutils_par_cor_vecs, 3},
    {"OMPutils_par_cor_matrix", (DL_FUNC) &OMPutils_par_cor_matrix, 2},
    {"OMPutils_rcpp_dist", (DL_FUNC) &OMPutils_rcpp_dist, 5},
    {"OMPutils_Rcpp_as_numeric_matrix", (DL_FUNC) &OMPutils_Rcpp_as_numeric_matrix, 1},
    {"OMPutils_par_mean", (DL_FUNC) &OMPutils_par_mean, 3},
    {"OMPutils_par_colMeans", (DL_FUNC) &OMPutils_par_colMeans, 4},
    {"OMPutils_par_rank", (DL_FUNC) &OMPutils_par_rank, 2},
    {"OMPutils_par_sort", (DL_FUNC) &OMPutils_par_sort, 1},
    {"OMPutils_par_sum", (DL_FUNC) &OMPutils_par_sum, 3},
    {"OMPutils_par_colSums", (DL_FUNC) &OMPutils_par_colSums, 4},
    {"OMPutils_par_var", (DL_FUNC) &OMPutils_par_var, 3},
    {"OMPutils_par_colVars", (DL_FUNC) &OMPutils_par_colVars, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_OMPutils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
