# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

par_cor_vecs <- function(x, y, threads = 1L) {
    .Call('OMPutils_par_cor_vecs', PACKAGE = 'OMPutils', x, y, threads)
}

par_cor_matrix <- function(X, threads = 1L) {
    .Call('OMPutils_par_cor_matrix', PACKAGE = 'OMPutils', X, threads)
}

#' Matrix Distance Measures
#'
#' Calculate the distance bewteen matrix rows using various distance measures.
#'
#' OpenMP is used to calculate improve calculation times.
#' @param x A numeric vector
#' @param na_rm Does nothing at present.
#' @param threads The number of threads to run calculation over
#' @export
rcpp_dist <- function(x, method = "euclidian", na_rm = FALSE, threads = 1L, display_progress = FALSE) {
    .Call('OMPutils_rcpp_dist', PACKAGE = 'OMPutils', x, method, na_rm, threads, display_progress)
}

Rcpp_as_numeric_matrix <- function(x) {
    .Call('OMPutils_Rcpp_as_numeric_matrix', PACKAGE = 'OMPutils', x)
}

#' Calculate the mean of a numeric vector
#' OpenMP is used to calculate improve calculation times.
#' @param x A numeric vector
#' @param na_rm Does nothing at present.
#' @param threads The number of threads to run calculation over
#' @export
par_mean <- function(x, na_rm = FALSE, threads = 1L) {
    .Call('OMPutils_par_mean', PACKAGE = 'OMPutils', x, na_rm, threads)
}

#' Calculate the column means for each column of a matrix.
#' OpenMP is used to calculate improve calculation times.
#' TODO: Needs to implement a multicore cliff.
#' @param x A numeric vector
#' @param na_rm Does nothing at present.
#' @param threads The number of threads to run calculation over
#' @export
par_colMeans <- function(x, na_rm = FALSE, threads = 1L, display_progress = FALSE) {
    .Call('OMPutils_par_colMeans', PACKAGE = 'OMPutils', x, na_rm, threads, display_progress)
}

par_rank <- function(x, threads = 1L) {
    .Call('OMPutils_par_rank', PACKAGE = 'OMPutils', x, threads)
}

#' @useDynLib OMPutils
#' @importFrom Rcpp sourceCpp
NULL

#' * Sort a vector using __gnu_parallel::sort.
#' * Code is not parallel, but is more efficient for numeric vectors than base R.
#' Parallel sort codes is https://gcc.gnu.org/onlinedocs/libstdc++/manual/parallel_mode_using.html
#' @param x A numeric vector
#' @export
par_sort <- function(x) {
    .Call('OMPutils_par_sort', PACKAGE = 'OMPutils', x)
}

#' Vector and Matrix Sums
#'
#' Calculate the sum of a vector
#'
#' Calculate the sum of a numeric vector
#' OpenMP is used to calculate improve calculation times.
#' @param x A numeric vector
#' @param na_rm Does nothing at present.
#' @param threads The number of threads to run calculation over
#' @export
par_sum <- function(x, na_rm = FALSE, threads = 1L) {
    .Call('OMPutils_par_sum', PACKAGE = 'OMPutils', x, na_rm, threads)
}

#' Calculate the column sums for each column of a matrix.
#' OpenMP is used to calculate improve calculation times.
#' TODO: Needs to implement a multicore cliff.
#' @param x A numeric vector
#' @param na_rm Does nothing at present.
#' @param threads The number of threads to run calculation over
#' @export
par_colSums <- function(x, na_rm = FALSE, threads = 1L, display_progress = FALSE) {
    .Call('OMPutils_par_colSums', PACKAGE = 'OMPutils', x, na_rm, threads, display_progress)
}

#' Calculate the varance of a vector.
#' Currently uses the Rcpp sugar implementation of the variance function.
#' TODO: Needs to implement a multicore cliff.
#' Based on https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance
#' @param x A numeric vector
#' @export
par_var <- function(x, na_rm = FALSE, threads = 1L) {
    .Call('OMPutils_par_var', PACKAGE = 'OMPutils', x, na_rm, threads)
}

#' Calculate the column variances of a matrix
#' * OpenMP is used to calculate improve calculation times.
#' TODO: Needs to implement a multicore cliff.
#' @param x A numeric vector
#' @param na_rm Does nothing at present.
#' @param threads The number of threads to run calculation over
#' @export
par_colVars <- function(x, na_rm = FALSE, threads = 1L) {
    .Call('OMPutils_par_colVars', PACKAGE = 'OMPutils', x, na_rm, threads)
}

